import assert from "node:assert/strict";import {mkdtemp,rm,writeFile,readFile} from "node:fs/promises";import {spawn} from "node:child_process";import os from "node:os";import path from "node:path";import test from "node:test";
const wait=async(url)=>{for(let i=0;i<80;i++){try{const r=await fetch(url);if(r.ok)return;}catch{}await new Promise(r=>setTimeout(r,50));}throw new Error("server not ready");};
test("canonical service identity, loopback, CORS, auth, size, and stale-shell policy fail closed",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"avatar-security-"));const port=19000+Math.floor(Math.random()*500);await writeFile(path.join(root,"avatars.json"),JSON.stringify({avatars:[{id:"avatar-sec",primaryName:"Secure"}],teams:[]}));await writeFile(path.join(root,"items.json"),JSON.stringify({cards:[{id:"item-sec",title:"Secure Item"}],agents:[],auditRuns:[],audit:{}}));
const child=spawn(process.execPath,["server/api.mjs","--host","127.0.0.1","--port",String(port)],{cwd:process.cwd(),env:{...process.env,HAPA_AVATAR_STORE:path.join(root,"avatars.json"),HAPA_ITEM_STORE:path.join(root,"items.json"),HAPA_AVATAR_OVERWIND_OUTBOX:path.join(root,"outbox.sqlite3"),HAPA_OVERWIND_DIR:path.join(root,"overwind"),HAPA_AVATAR_ADMIN_TOKEN:"security-token",HAPA_AVATAR_MAX_REQUEST_BYTES:"1024"},stdio:["ignore","pipe","pipe"]});
try{await wait(`http://127.0.0.1:${port}/api/health`);const identity=await fetch(`http://127.0.0.1:${port}/api/service-identity`).then(r=>r.json());assert.equal(identity.serviceId,"hapa-avatar-builder");assert.equal(identity.bind.loopback,true);assert.equal(identity.populations.canonicalAvatarCards.count,1);assert.equal(identity.populations.canonicalItemCards.count,1);assert.equal(identity.populations.combinedViewIsCanonical,false);assert.equal(identity.legacyPorts[8787],"canonical API");assert.match(identity.legacyPorts[8797],/same service identity/);
const denied=await fetch(`http://127.0.0.1:${port}/api/service-identity`,{headers:{Origin:"https://evil.example"}});assert.equal(denied.status,403);const allowed=await fetch(`http://127.0.0.1:${port}/api/service-identity`,{headers:{Origin:"http://127.0.0.1:5178"}});assert.equal(allowed.headers.get("access-control-allow-origin"),"http://127.0.0.1:5178");
const unauthorized=await fetch(`http://127.0.0.1:${port}/api/overwind/card-origin/migrate-legacy`,{method:"POST"});assert.equal(unauthorized.status,401);const tooLarge=await fetch(`http://127.0.0.1:${port}/api/overwind/card-origin/operation`,{method:"POST",headers:{authorization:"Bearer security-token","content-type":"application/json"},body:JSON.stringify({padding:"x".repeat(70000)})});assert.equal(tooLarge.status,413);
const source=await readFile("server/api.mjs","utf8");assert.equal(source.includes("shell-from-last-shell-cache"),false);assert.match(source,/stale_overwind_shell_rejected/);const launcher=await readFile("scripts/launch-desktop-dedicated.zsh","utf8");assert.match(launcher,/HAPA_AVATAR_BIND_HOST:-127\.0\.0\.1/);
}finally{child.kill("SIGTERM");await new Promise(r=>child.once("exit",r));await rm(root,{recursive:true,force:true});}});
